=== avivAlfa/Numberiada/out/production/Numberiada_NA/resources/Numberiada.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GameDescriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GameType">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Basic"/>
							<xs:enumeration value="Advance"/>
							<xs:enumeration value="AdvanceDynamic"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Board">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Size" type="xs:integer"/>
							<xs:element name="Structure">
								<xs:complexType>
									<xs:choice>
										<xs:element name="Range">
											<xs:complexType>
												<xs:attribute name="from" type="xs:int" use="required"/>
												<xs:attribute name="to" type="xs:int" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Squares">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Square" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:integer">
																	<xs:attribute name="row" type="xs:positiveInteger" use="required"/>
																	<xs:attribute name="column" type="xs:positiveInteger" use="required"/>
																	<xs:attribute name="color" use="required">
																		<xs:simpleType>
																			<xs:restriction base="xs:integer">
																				<xs:minInclusive value="0"/>
																				<xs:maxInclusive value="6"/>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="Marker">
														<xs:complexType>
															<xs:attribute name="row" type="xs:positiveInteger" use="required"/>
															<xs:attribute name="column" type="xs:positiveInteger" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Random"/>
												<xs:enumeration value="Explicit"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Players" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Player" minOccurs="3" maxOccurs="6">
								<xs:complexType>
									<xs:all>
										<xs:element name="Name" type="xs:string"/>
										<xs:element name="Type">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Human"/>
													<xs:enumeration value="Computer"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Color">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="1" fixed="true"/>
													<xs:maxInclusive value="6" fixed="true"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:all>
									<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DynamicPlayers" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="gameTitle" type="xs:string" use="required"/>
						<xs:attribute name="totalPlayers" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="3"/>
									<xs:maxInclusive value="6"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== avivAlfa/Numberiada/src/resources/numberiada_7_advanced_explicit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<GameDescriptor xsi:noNamespaceSchemaLocation="Numberiada.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GameType>Advance</GameType>
	<Board>
		<Size>7</Size>
		<Structure type="Explicit">
			<Squares>
				<Square row="1" column="2" color="1">
					-3
				</Square>
				<Square row="1" column="4" color="2">
					4
				</Square>
				<Square row="3" column="5" color="3">
					5
				</Square>
				<Square row="4" column="4" color="4">
					2
				</Square>
				<Square row="6" column="1" color="1">
					3
				</Square>
				<Square row="7" column="7" color="2">
					-4
				</Square>
				<Square row="6" column="6" color="3">
					12
				</Square>
				<Square row="5" column="5" color="4">
					3
				</Square>
				<Marker row="4" column="3"/>
			</Squares>
		</Structure>
	</Board>	
	<Players>
		<Player id="233">
			<Name>Mushon</Name>
			<Type>Human</Type>
			<Color>1</Color>
		</Player>
		<Player id="21233">
			<Name>Avrum</Name>
			<Type>Human</Type>
			<Color>2</Color>
		</Player>
		<Player id="456">
			<Name>Nachtze</Name>
			<Type>Computer</Type>
			<Color>3</Color>
		</Player>
		<Player id="784353">
			<Name>Aralle</Name>
			<Type>Human</Type>
			<Color>4</Color>
		</Player>
	</Players>	
</GameDescriptor>

=== avivAlfa/Numberiada/out/production/Numberiada_NA/resources/numberiada_7_advanced_random.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<GameDescriptor xsi:noNamespaceSchemaLocation="Numberiada.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GameType>Advance</GameType>
	<Board>
		<Size>7</Size>
		<Structure type="Random">
			<Range to="10" from="-5"/>
		</Structure>
	</Board>	
	<Players>
		<Player id="233">
			<Name>Mushon</Name>
			<Type>Human</Type>
			<Color>1</Color>
		</Player>
		<Player id="21233">
			<Name>Avrum</Name>
			<Type>Human</Type>
			<Color>2</Color>
		</Player>
		<Player id="456">
			<Name>Nachtze</Name>
			<Type>Computer</Type>
			<Color>3</Color>
		</Player>
		<Player id="784353">
			<Name>Aralle</Name>
			<Type>Human</Type>
			<Color>4</Color>
		</Player>
	</Players>
</GameDescriptor>

=== avivAlfa/Numberiada/src/resources/r.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<GameDescriptor xsi:noNamespaceSchemaLocation="Numberiada.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GameType>Basic</GameType>
	<Board>
		<Size>5</Size>
		<Structure type="Random">
			<Range from="5" to="6"/>
		</Structure>
	</Board>	
	<Players>
		<Player id="1">
			<Name>RowPlayer</Name>
			<Type>Human</Type>
			<Color>0</Color>
		</Player>
		<Player id="2">
			<Name>ColumnPlayer</Name>
			<Type>Computer</Type>
			<Color>0</Color>
		</Player>
	</Players>	
</GameDescriptor>

=== avivAlfa/Numberiada/src/resources/numberiada_7_basic_explicit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<GameDescriptor xsi:noNamespaceSchemaLocation="Numberiada.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GameType>Basic</GameType>
	<Board>
		<Size>8</Size>
		<Structure type="Explicit">
			<Squares>
				<Square row="1" column="2" color="0">
					-3
				</Square>
				<Square row="1" column="4" color="0">
					4
				</Square>
				<Square row="3" column="5" color="0">
					5
				</Square>
				<Square row="4" column="4" color="0">
					2
				</Square>
				<Square row="6" column="1" color="0">
					3
				</Square>
				<Square row="7" column="7" color="0">
					-4
				</Square>
				<Square row="6" column="6" color="0">
					12
				</Square>
				<Marker row="4" column="3"/>
			</Squares>
		</Structure>
	</Board>	
</GameDescriptor>
